### ISSUE TITLE
Question on the id in backup zip file name

### ISSUE THREAD

**Issue by alan0xd7** [bovarysme/memories#1]
Hey, thanks for creating this program! It helped a lot reading some old backups I have.

I'm wondering if you have any information about the numeric id that's part of the backup file name? `LINE_Android-backup-chat<id>.zip` 

As far as I can tell, it uses the same id every time for the same person, so maybe it is based on the `mid`? But I can't figure out how it is generated. Any insight is appreciated, thank you.

**Comment by bovarysme** [comment]
Hi, I'm glad this project helped you!

You're right, the generated ID is based on your and your chat partner's accounts `PROFILE_MID`. The algorithm to generate the ID is the following:
```
(THEIR_MID + YOUR_MID).hashCode() + THEIR_MID[16] + YOUR_MID[11]
```
Where `hashCode()` is the Java method mentioned in the README, `+` is the string concatenation, and `[x]` is the `x + 1` character in the string.
Please note that the resulting ID can have a leading minus sign (e.g. `-084891507985`).

The algorithm to generate the ID from group chats is a bit different. I can look it up for you if you need it.

I hope this helps! Don't hesitate to ask any other questions in this issue thread. :)

**Comment by alan0xd7** [comment]
Hey, thanks for this! Hopefully it can help to organize all the backups files I have. 

I think even when you know all your contacts' `mid`s (from the app's SQLite database on the phone), it's still pretty hard to tell which backup belongs to who because it seems the `mid`s change quite often (when people get new phones).
